baseURL = 'https://petretiberiu.dev/'
locale = 'en-us'
title = 'Blog (titlu provizoriu — test deploy 2026-08-17)'
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
